apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-pdf-converter-app
  namespace: wpc-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: word-pdf-converter-app
  template:
    metadata:
      labels:
        app: word-pdf-converter-app
    spec:
      containers:
      - name: word-pdf-converter-app
        image: manodayahire/wordtopdf:13
        
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: MYSQL_HOST
          value: "mysql-service"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "converter_db"
        - name: MONGO_HOST
          value: "mongodb-service"
        - name: MONGO_PORT
          value: "27017"
        
---
apiVersion: v1
kind: Service

metadata:
  name: word-pdf-converter-service
  namespace: wpc-ns
spec:
  type: NodePort
  selector:
    app: word-pdf-converter-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30202
